<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIvrkr0m\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIvrkr0m/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerIvrkr0m.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerIvrkr0m\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerIvrkr0m\appProdProjectContainer([
    'container.build_hash' => 'Ivrkr0m',
    'container.build_id' => '2c0f911e',
    'container.build_time' => 1684155284,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIvrkr0m');
