<?php
define('_DB_SERVER_', 'rdbms.strato.de');
define('_DB_NAME_', 'DB2331749');
define('_DB_USER_', 'U2331749');
define('_DB_PASSWD_', '7LPU3b16HEAvBoMVT');
define('_DB_PREFIX_', 'prstshp_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheFs');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', 'pePc2tjmGwuZDPOMVkDdSwBeaVs4FX3G4sX4qwqNmexz4dLdshRf7MJD');
define('_COOKIE_IV_', 'WFz3vYMY');
define('_PS_CREATION_DATE_', '2015-10-29');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.0.9');
define('_RIJNDAEL_KEY_', 'SuaGVxGVKbedcSqsAv9uOOSbC5ehJHaL');
define('_RIJNDAEL_IV_', 'AAAAAAAAAAAAAAAAAAAAAA==');